### ISSUE TITLE
Need to redefine Timestamp pattern

### ISSUE THREAD

**Issue by anlklsim** [StephenOTT/STIX-Java#93]
According to the spec, the sub-seconds are optional in any field that uses a timestamp.  The format is " YYYY-MM-DDTHH:mm:ss[.s+]Z where the “s+” represents 1 or more sub-second values. The brackets denote that sub-second precision is optional, and that if no digits are provided, the decimal place MUST NOT be present."

Therefore, the code needs to accommodate that for validation and serialization.

**Comment by StephenOTT** [comment]
This work has started and is also in discussion with STIX CTI user group mailing list

**Comment by StephenOTT** [comment]
This work is pending merge as part of https://github.com/StephenOTT/STIX-Java/pull/94
